import 'package:confianza_admin/modulos/inventario/vista_inventario.dart';

List<PedidoInventario> getInitialMockData() {
  return [
    PedidoInventario(
      id: '1',
      nombre: 'Catpillar Tractor-Scrapers',
      descripcion:
          'Carga rápida, alta velocidad de desplazamiento y capacidad para realizar trabajo continuo.',
      proveedor: 'Catpillar',
      fecha: '11/03/2017',
      pagadoPor: 'Eric Hoffman',
      referencia: 'JKU2439800001838',
      descuento: 350.00,
      impuesto: 733.50,
      envio: 123.50,
      productos: [
        ProductoPedido(
          nombre: 'Studio Pro Wireless',
          sku: 'SKU-131200238',
          costo: 188.00,
          bodegas: [
            BodegaDistribucion(nombre: 'Brand Depot', cantidad: 39),
            BodegaDistribucion(nombre: 'Warehously', cantidad: 10),
            BodegaDistribucion(nombre: 'Pod Capital', cantidad: 10),
          ],
          descripcion: 'Over-ear active noise cancelling',
          codigoBarra: 'STP-882-BLU',
          categoria: 'Electrónica',
          proveedor: 'Bodega',
          cantidadMinima: 1,
          tipoProducto: 'Normal',
          fechaIngresado: '19-05-26',
        ),
        ProductoPedido(
          nombre: 'Desbrozadoras de Maleza',
          sku: 'SKU-DESB-002',
          costo: 117.99,
          bodegas: [BodegaDistribucion(nombre: 'Brand Depot', cantidad: 88)],
          descripcion:
              'Elimina maleza densa y vegetación descontrolada con facilidad.',
          codigoBarra: 'STP-900-BLU',
          categoria: 'Herramientas',
          proveedor: 'General',
          cantidadMinima: 5,
          tipoProducto: 'Normal',
          fechaIngresado: '12-04-26',
        ),
        ProductoPedido(
          nombre: 'Paralelo de Acoplamiento de Cargador',
          sku: 'SKU-PARA-003',
          costo: 789.00,
          bodegas: [BodegaDistribucion(nombre: 'Pod Capital', cantidad: 39)],
          descripcion:
              'Acoplamiento robusto para cargadoras y excavadoras de alto tonelaje.',
          codigoBarra: 'STP-121-Z',
          categoria: 'Tractores',
          proveedor: 'Catpillar',
          cantidadMinima: 2,
          tipoProducto: 'Normal',
          fechaIngresado: '13-03-17',
        ),
      ],
      lotes: [
        LotePedido(
          codigo: 'LOT-2026-001',
          stock: 59,
          fechaIngreso: '11/03/2017',
          fechaVencimiento: '28-02-2027',
          costo: 188.00,
          precioVenta: 250.00,
        ),
        LotePedido(
          codigo: 'LOT-2026-002',
          stock: 88,
          fechaIngreso: '12/03/2017',
          fechaVencimiento: '12-03-2028',
          costo: 117.99,
          precioVenta: 180.00,
        ),
        LotePedido(
          codigo: 'LOT-2026-003',
          stock: 39,
          fechaIngreso: '13/03/2017',
          fechaVencimiento: '13-03-2028',
          costo: 789.00,
          precioVenta: 1100.00,
        ),
      ],
    ),
    PedidoInventario(
      id: '2',
      nombre: 'Cucharas de Grata',
      descripcion: 'Para sujetar y transportar material empacado.',
      proveedor: 'General',
      fecha: '15/04/2026',
      pagadoPor: 'Admin',
      referencia: 'REF-GRAB-001',
      descuento: 100.00,
      impuesto: 150.00,
      envio: 50.00,
      productos: [
        ProductoPedido(
          nombre: 'Cucharas de Grata',
          sku: 'SKU-GRAB-004',
          costo: 250.00,
          bodegas: [BodegaDistribucion(nombre: 'Brand Depot', cantidad: 10)],
          descripcion: 'Para sujetar y transportar material empacado.',
          codigoBarra: 'STP-777-GRB',
          categoria: 'Herramientas',
          proveedor: 'General',
          cantidadMinima: 1,
          tipoProducto: 'Normal',
          fechaIngresado: '15-04-26',
        ),
      ],
      lotes: [
        LotePedido(
          codigo: 'LOT-2026-004',
          stock: 10,
          fechaIngreso: '15/04/2026',
          fechaVencimiento: '15-04-2029',
          costo: 250.00,
          precioVenta: 350.00,
        ),
      ],
    ),
    PedidoInventario(
      id: '3',
      nombre: 'Paralelo de Acoplamiento de Cargador',
      descripcion: 'Cargador de varillaje en Z optimizado por Cat.',
      proveedor: 'Catpillar',
      fecha: '20/05/2026',
      pagadoPor: 'John Doe',
      referencia: 'REF-PAR-002',
      descuento: 0.00,
      impuesto: 300.00,
      envio: 80.00,
      productos: [
        ProductoPedido(
          nombre: 'Paralelo de Acoplamiento de Cargador',
          sku: 'SKU-PARA-005',
          costo: 800.00,
          bodegas: [BodegaDistribucion(nombre: 'Warehously', cantidad: 1)],
          descripcion: 'Cargador de varillaje en Z optimizado por Cat.',
          codigoBarra: 'STP-882-Z',
          categoria: 'Tractores',
          proveedor: 'Catpillar',
          cantidadMinima: 1,
          tipoProducto: 'Normal',
          fechaIngresado: '20-05-26',
        ),
      ],
      lotes: [
        LotePedido(
          codigo: 'LOT-2026-005',
          stock: 1,
          fechaIngreso: '20/05/2026',
          fechaVencimiento: '20-05-2029',
          costo: 800.00,
          precioVenta: 1200.00,
        ),
      ],
    ),
  ];
}
